<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="SBR-DEVPTL-07" ignored="0" name="RetryMultipleFailedTestCases" tests="7" failures="2" timestamp="07 Oct 2018 11:02:44 GMT" time="0.093" errors="0">
  <testcase name="Test1" time="0.0" classname="MyTests.MyTests">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase name="Test1" time="0.0" classname="MyTests.MyTests">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase name="Test1" time="0.015" classname="MyTests.MyTests">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at MyTests.MyTests.Test1(MyTests.java:13)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- Test1 -->
  <testcase name="Test2" time="0.0" classname="MyTests.MyTests">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase name="Test2" time="0.0" classname="MyTests.MyTests">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase name="Test2" time="0.0" classname="MyTests.MyTests">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at MyTests.MyTests.Test2(MyTests.java:19)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- Test2 -->
  <testcase name="Test3" time="0.0" classname="MyTests.MyTests"/>
</testsuite> <!-- RetryMultipleFailedTestCases -->
